[script]
name = "Fedora Post-Install Script"
version = "2.0.0"
author = "cuey"
repository = "https://github.com/cuey78/Fedora-Post-Install"

[settings]
cache_dir = ".cache"
parallel_install = true
max_jobs = 4
log_file = "fedora-post-install.log"

[dependencies]
required = ["dialog"]

[ui]
banner_color = "cyan"
menu_color = "blue"
progress_color = "green"

[plugins]
directory = "plugins"
pattern = "*.sh"

[menu_categories]
# 0 = "load but not in any menu"
1 = "Main"
2 = "Utilities"
3 = "Advanced Features"
4 = "Development"
